package net.siudek;

import lombok.Value;

/**
 * Simple Lombok type to test code coverage with Lombok autogenerated methods / accessors e.t.c
 * Expected: class is marked as fully covered
 */
@Value(staticConstructor = "of")
public class IncreaseResult {
    private int originalValue;
    private int incrementedValue;
}
